// <auto-generated />
namespace AuroraProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class GIG_INFLUENCER_RELATION : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GIG_INFLUENCER_RELATION));
        
        string IMigrationMetadata.Id
        {
            get { return "202004020606413_GIG_INFLUENCER_RELATION"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
